/*Write a program using a function which calculates the sum and average of two
numbers. Use pointers and print the address of sum and average in main().*/

//not done yet......
//not done yet......
//not done yet......
//not done yet......
//not done yet......
//not done yet......
//not done yet......
//not done yet......
//not done yet......